number = int(input("enter number "))
print("table",int(number))
print(f"{int(number)}*1={int(number)}")
print(f"{int(number)}*2={int(number)*2}")
print(f"{number}*3={number*3}")
print(f"{number}*4={number*4}")
print(f"{number}*5={number*5}")
print(f"{number}*6={number*6}")
print(f"{number}*7={number*7}")
print(f"{number}*8={number*8}")
print(f"{number}*9={number*9}")
print(f"{number}*10={number*10}")
